version: '3.1'

services:
#  backend:
#    image: 'purap1e/spring-docker-image'
#    container_name: bootcamp
#    depends_on:
#      - db
#    restart: always
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=password
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    ports:
#      - 8080:8080

  db:
    image: 'postgres'
    container_name: pg-server
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
